// <auto-generated />
using System;
using BevosTunesMVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BevosTunesMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BevosTunesMVC.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"));

                    b.Property<string>("AlbumCoverURL")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AlbumID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumArtist", b =>
                {
                    b.Property<int>("AlbumArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumArtistID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.HasKey("AlbumArtistID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ArtistID");

                    b.ToTable("AlbumArtists");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumGenre", b =>
                {
                    b.Property<int>("AlbumGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumGenreID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("AlbumGenreID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("GenreID");

                    b.ToTable("AlbumGenres");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumReview", b =>
                {
                    b.Property<int>("AlbumReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumReviewID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovingEmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AlbumReviewID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ApprovingEmployeeID");

                    b.HasIndex("CustomerID");

                    b.ToTable("AlbumReviews");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumSong", b =>
                {
                    b.Property<int>("AlbumSongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumSongID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("SongID")
                        .HasColumnType("int");

                    b.HasKey("AlbumSongID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("SongID");

                    b.ToTable("AlbumSongs");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.ArtistGenre", b =>
                {
                    b.Property<int>("ArtistGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistGenreID"));

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("ArtistGenreID");

                    b.HasIndex("ArtistID");

                    b.HasIndex("GenreID");

                    b.ToTable("ArtistGenres");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.ArtistReview", b =>
                {
                    b.Property<int>("ArtistReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistReviewID"));

                    b.Property<int?>("ApprovingEmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ArtistReviewID");

                    b.HasIndex("ApprovingEmployeeID");

                    b.HasIndex("ArtistID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ArtistReviews");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SongID")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SongID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.CreditCard", b =>
                {
                    b.Property<int>("CreditCardID")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CreditCardID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Discount", b =>
                {
                    b.Property<int>("DiscountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountID"));

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SongID")
                        .HasColumnType("int");

                    b.HasKey("DiscountID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("SongID");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.FeaturedItem", b =>
                {
                    b.Property<int>("FeaturedItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeaturedItemID"));

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SongID")
                        .HasColumnType("int");

                    b.HasKey("FeaturedItemID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ArtistID");

                    b.HasIndex("SongID");

                    b.ToTable("FeaturedItems");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("CreditCardID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("GiftRecipientEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CreditCardID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("SongID")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("OrderID");

                    b.HasIndex("SongID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongID"));

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("SongID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.SongGenre", b =>
                {
                    b.Property<int>("SongGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongGenreID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("SongID")
                        .HasColumnType("int");

                    b.HasKey("SongGenreID");

                    b.HasIndex("GenreID");

                    b.HasIndex("SongID");

                    b.ToTable("SongGenres");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.SongReview", b =>
                {
                    b.Property<int>("SongReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongReviewID"));

                    b.Property<int?>("ApprovingEmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SongID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SongReviewID");

                    b.HasIndex("ApprovingEmployeeID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SongID");

                    b.ToTable("SongReviews");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumArtist", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Artist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumGenre", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumReview", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("AlbumReviews")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Employee", "ApprovingEmployee")
                        .WithMany("ApprovedAlbumReviews")
                        .HasForeignKey("ApprovingEmployeeID");

                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("AlbumReviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("ApprovingEmployee");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.AlbumSong", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.ArtistGenre", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Artist", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Genre", "Genre")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.ArtistReview", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Employee", "ApprovingEmployee")
                        .WithMany("ApprovedArtistReviews")
                        .HasForeignKey("ApprovingEmployeeID");

                    b.HasOne("BevosTunesMVC.Models.Artist", "Artist")
                        .WithMany("ArtistReviews")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("ArtistReviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovingEmployee");

                    b.Navigation("Artist");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.CartItem", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("CartItems")
                        .HasForeignKey("AlbumID");

                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("CartItems")
                        .HasForeignKey("SongID");

                    b.Navigation("Album");

                    b.Navigation("Customer");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.CreditCard", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("CreditCards")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Discount", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("Discounts")
                        .HasForeignKey("AlbumID");

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("Discounts")
                        .HasForeignKey("SongID");

                    b.Navigation("Album");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.FeaturedItem", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("FeaturedItems")
                        .HasForeignKey("AlbumID");

                    b.HasOne("BevosTunesMVC.Models.Artist", "Artist")
                        .WithMany("FeaturedItems")
                        .HasForeignKey("ArtistID");

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("FeaturedItems")
                        .HasForeignKey("SongID");

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Order", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.CreditCard", "CreditCard")
                        .WithMany("Orders")
                        .HasForeignKey("CreditCardID");

                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.OrderItem", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Album", "Album")
                        .WithMany("OrderItems")
                        .HasForeignKey("AlbumID");

                    b.HasOne("BevosTunesMVC.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("OrderItems")
                        .HasForeignKey("SongID");

                    b.Navigation("Album");

                    b.Navigation("Order");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Song", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.SongGenre", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Genre", "Genre")
                        .WithMany("SongGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("SongGenres")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.SongReview", b =>
                {
                    b.HasOne("BevosTunesMVC.Models.Employee", "ApprovingEmployee")
                        .WithMany("ApprovedSongReviews")
                        .HasForeignKey("ApprovingEmployeeID");

                    b.HasOne("BevosTunesMVC.Models.Customer", "Customer")
                        .WithMany("SongReviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BevosTunesMVC.Models.Song", "Song")
                        .WithMany("SongReviews")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovingEmployee");

                    b.Navigation("Customer");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Album", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("AlbumGenres");

                    b.Navigation("AlbumReviews");

                    b.Navigation("AlbumSongs");

                    b.Navigation("CartItems");

                    b.Navigation("Discounts");

                    b.Navigation("FeaturedItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Artist", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("ArtistGenres");

                    b.Navigation("ArtistReviews");

                    b.Navigation("FeaturedItems");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.CreditCard", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Customer", b =>
                {
                    b.Navigation("AlbumReviews");

                    b.Navigation("ArtistReviews");

                    b.Navigation("CartItems");

                    b.Navigation("CreditCards");

                    b.Navigation("Orders");

                    b.Navigation("SongReviews");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Employee", b =>
                {
                    b.Navigation("ApprovedAlbumReviews");

                    b.Navigation("ApprovedArtistReviews");

                    b.Navigation("ApprovedSongReviews");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Genre", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("ArtistGenres");

                    b.Navigation("SongGenres");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BevosTunesMVC.Models.Song", b =>
                {
                    b.Navigation("AlbumSongs");

                    b.Navigation("CartItems");

                    b.Navigation("Discounts");

                    b.Navigation("FeaturedItems");

                    b.Navigation("OrderItems");

                    b.Navigation("SongGenres");

                    b.Navigation("SongReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
